// Provider configuration: API key management, connection testing, multi-provider support.
//
// Supports four provider types:
//   1. anthropic    — Anthropic API (Claude models)
//   2. openai       — OpenAI API (GPT models)
//   3. openrouter   — OpenRouter (any model via OpenAI-compatible API)
//   4. openai-compat — Any OpenAI-compatible endpoint (Ollama, vLLM, etc.)
//
// Keys are resolved in order:
//   1. Environment variables
//   2. Project .env file (multiagentworld/.env)
//   3. Flamebird .env (~/.flamebird/.env) — picks up LLM_API_KEY for OpenRouter
//   4. Interactive setup (saved to project .env)

import fs from "fs";
import path from "path";
import os from "os";

export type ProviderType = "anthropic" | "openai" | "openrouter" | "openai-compat";

export type ProviderConfig = {
  type: ProviderType;
  apiKey: string;
  baseUrl: string;
  model: string;
  workspaceId?: string | null;
};

export type ProviderStatus = {
  available: boolean;
  type: ProviderType | null;
  model: string | null;
  error: string | null;
};

// --- Model → provider resolution ---

const ANTHROPIC_MODELS = ["claude-opus-4-6", "claude-sonnet-4-6", "claude-haiku-4-5", "claude-sonnet-4-5-20250514", "claude-haiku-4-5-20251001"];
const OPENAI_MODELS = ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "o3-mini"];

function normalizeAnthropicModelForOpenRouter(model: string): string {
  const known: Record<string, string> = {
    "claude-haiku-4-5": "anthropic/claude-haiku-4.5",
    "claude-haiku-4-5-20251001": "anthropic/claude-haiku-4.5",
    "claude-sonnet-4-5-20250514": "anthropic/claude-sonnet-4.5",
    "claude-sonnet-4-6": "anthropic/claude-sonnet-4.6",
    "claude-opus-4-6": "anthropic/claude-opus-4.6",
  };
  if (known[model]) {
    return known[model];
  }
  return `anthropic/${model}`;
}

function normalizeOpenAIModelForOpenRouter(model: string): string {
  return `openai/${model}`;
}

export function resolveProviderType(model: string): ProviderType | null {
  if (model.startsWith("claude-") || ANTHROPIC_MODELS.includes(model)) return "anthropic";
  if (model.startsWith("gpt-") || model.startsWith("o3") || model.startsWith("o4") || OPENAI_MODELS.includes(model)) return "openai";
  // Anything with a slash (e.g., "anthropic/claude-sonnet-4") is likely OpenRouter format
  if (model.includes("/")) return "openrouter";
  return "openai-compat";
}

// --- .env file management ---

function loadEnvFile(envPath: string): Record<string, string> {
  if (!fs.existsSync(envPath)) return {};
  const content = fs.readFileSync(envPath, "utf8");
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx < 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function saveEnvFile(envPath: string, vars: Record<string, string>): void {
  const existing = loadEnvFile(envPath);
  const merged = { ...existing, ...vars };
  const lines = [
    "# Agent Society — LLM Provider Configuration",
    "# Generated by multiagent:society setup",
    "",
  ];
  for (const [key, value] of Object.entries(merged)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  fs.writeFileSync(envPath, lines.join("\n"), "utf8");
}

// --- Key resolution (cascading search) ---

function getEnvVar(key: string, projectRoot: string): string | undefined {
  // 1. Process environment
  if (process.env[key]) return process.env[key];
  // 2. Project .env file
  const projectEnv = loadEnvFile(path.join(projectRoot, ".env"));
  if (projectEnv[key]) return projectEnv[key];
  // 3. Flamebird .env (shared config)
  const flamebirdEnv = loadEnvFile(path.join(os.homedir(), ".flamebird", ".env"));
  if (flamebirdEnv[key]) return flamebirdEnv[key];
  return undefined;
}

export function resolveApiKey(providerType: ProviderType, projectRoot: string): string | null {
  switch (providerType) {
    case "anthropic":
      return getEnvVar("ANTHROPIC_API_KEY", projectRoot) ?? null;
    case "openai":
      return getEnvVar("OPENAI_API_KEY", projectRoot) ?? null;
    case "openrouter":
      return getEnvVar("OPENROUTER_KEY", projectRoot)
        ?? getEnvVar("LLM_API_KEY", projectRoot)
        ?? getEnvVar("OPENAI_API_KEY", projectRoot)
        ?? null;
    case "openai-compat":
      return getEnvVar("OPENAI_API_KEY", projectRoot)
        ?? getEnvVar("LLM_API_KEY", projectRoot)
        ?? null;
  }
}

export function resolveBaseUrl(providerType: ProviderType, projectRoot: string): string {
  switch (providerType) {
    case "anthropic":
      return getEnvVar("ANTHROPIC_BASE_URL", projectRoot) ?? "https://api.anthropic.com";
    case "openai":
      return getEnvVar("OPENAI_BASE_URL", projectRoot) ?? "https://api.openai.com";
    case "openrouter":
      return "https://openrouter.ai/api";
    case "openai-compat":
      return getEnvVar("OPENAI_BASE_URL", projectRoot) ?? "http://localhost:11434/v1";
  }
}

export function resolveProvider(model: string, projectRoot: string): ProviderConfig | null {
  const type = resolveProviderType(model);
  if (!type) return null;

  const apiKey = resolveApiKey(type, projectRoot);

  // Fallback: if anthropic/openai key not found, try OpenRouter
  if (!apiKey && (type === "anthropic" || type === "openai")) {
    const orKey = resolveApiKey("openrouter", projectRoot);
    if (orKey) {
      // Route through OpenRouter with the original model name
      const orModel = type === "anthropic"
        ? normalizeAnthropicModelForOpenRouter(model)
        : normalizeOpenAIModelForOpenRouter(model);
      return {
        type: "openrouter",
        apiKey: orKey,
        baseUrl: "https://openrouter.ai/api",
        model: orModel,
        workspaceId: null,
      };
    }
    return null;
  }

  if (!apiKey) return null;

  return {
    type,
    apiKey,
    baseUrl: resolveBaseUrl(type, projectRoot),
    model,
    workspaceId: type === "anthropic" ? (getEnvVar("ANTHROPIC_WORKSPACE_ID", projectRoot) ?? null) : null,
  };
}

// --- Connection testing ---

export async function testProvider(config: ProviderConfig): Promise<ProviderStatus> {
  try {
    if (config.type === "anthropic") {
      const res = await fetch(`${config.baseUrl}/v1/messages`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": config.apiKey,
          "anthropic-version": "2023-06-01",
          ...(config.workspaceId ? { "anthropic-workspace-id": config.workspaceId } : {}),
        },
        body: JSON.stringify({
          model: config.model,
          max_tokens: 5,
          messages: [{ role: "user", content: "Say OK" }],
        }),
      });
      if (!res.ok) {
        const body = await res.text();
        return { available: false, type: config.type, model: config.model, error: `HTTP ${res.status}: ${body.slice(0, 200)}` };
      }
      return { available: true, type: config.type, model: config.model, error: null };
    } else {
      // OpenAI, OpenRouter, and OpenAI-compatible all use the same format
      const res = await fetch(`${config.baseUrl}/v1/chat/completions`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${config.apiKey}`,
        },
        body: JSON.stringify({
          model: config.model,
          max_tokens: 5,
          messages: [{ role: "user", content: "Say OK" }],
        }),
      });
      if (!res.ok) {
        const body = await res.text();
        return { available: false, type: config.type, model: config.model, error: `HTTP ${res.status}: ${body.slice(0, 200)}` };
      }
      return { available: true, type: config.type, model: config.model, error: null };
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    return { available: false, type: config.type, model: config.model, error: msg };
  }
}

// --- Check what's available ---

export function checkProviderStatus(model: string, projectRoot: string): { ready: boolean; providerType: ProviderType | null; missingKey: boolean; keyEnvVar: string | null } {
  const provider = resolveProvider(model, projectRoot);
  if (provider) {
    return { ready: true, providerType: provider.type, missingKey: false, keyEnvVar: null };
  }

  const type = resolveProviderType(model);
  const keyEnvVar = type === "anthropic" ? "ANTHROPIC_API_KEY" : type === "openai" ? "OPENAI_API_KEY" : "LLM_API_KEY";

  return {
    ready: false,
    providerType: type,
    missingKey: true,
    keyEnvVar,
  };
}

// --- Save key to .env ---

export function saveApiKey(providerType: ProviderType, apiKey: string, projectRoot: string, baseUrl?: string): void {
  const envPath = path.join(projectRoot, ".env");
  const vars: Record<string, string> = {};

  if (providerType === "anthropic") {
    vars["ANTHROPIC_API_KEY"] = apiKey;
  } else if (providerType === "openrouter") {
    vars["OPENROUTER_KEY"] = apiKey;
  } else {
    vars["OPENAI_API_KEY"] = apiKey;
  }

  if (baseUrl) {
    if (providerType === "anthropic") {
      vars["ANTHROPIC_BASE_URL"] = baseUrl;
    } else if (providerType !== "openrouter") {
      vars["OPENAI_BASE_URL"] = baseUrl;
    }
  }

  saveEnvFile(envPath, vars);
}

// --- Redact key for display ---

export function redactKey(key: string): string {
  if (key.length <= 8) return "****";
  return key.slice(0, 4) + "..." + key.slice(-4);
}
